version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  # We are disabling Dependabot for Node repos until it supports
  # grouped updates:
  # https://github.com/dependabot/dependabot-core/issues/1190
  open-pull-requests-limit: 0
